spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: taskuser
    password: taskpass
    driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8090

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    sendMessageTimeout: 10000
    retryTimesWhenSendFailed: 3
    group: notification_producer_group

app:
  rocketmq:
    notification-topic: notification-topic
  redis:
    recent-list-key: "recent_notifications"
    notification-key-prefix: "notification:"
